# ================================
# System
server:
  port: 8002
    

# ================================
# Spring
spring:
  # --------------
  # Profiles
  profiles:
    active: local
  # --------------
  # Cloud
  application:
    name: jonastalk-auth-api
  # --------------
  # Web
  web:
    resources:
      static-locations: /resources/
      cache:
        period: 10
  # --------------
  # MVC
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER # For Swagger
  # --------------
  # Server Auto restart
  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false

      
# ================================
# Eureka
eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8999/eureka


# ================================
# Jasypt
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password : k/hUpdMKgvyR4Hf+Sv4SRQ== # Encrypted in AES-256
    
          
# ================================
# RSA
rsa:
  filepath:
    jwt:
      privateKey: private_key_jwt.pem
      publicKey: public_key_jwt.pem
    password:
      privateKey: private_key_password.pem
      publicKey: public_key_password.pem
  
  
  
# ================================ 
# Logging
logging:
  file:
    path: ./logs
    name: web-auth-api-gw.log
    max-history: 30
  pattern:
    file: "[%d{yyyy-MM-dd HH:mm:ss.SSS}][%-5level][%logger.%method:line - %line] - %msg%n"
    console: "[%d{yyyy-MM-dd HH:mm:ss.SSS}][%-5level][%logger.%method - %line] - %msg%n"
    rolling-file-name: "./logs/web-blog-jonaslog.%d{yyyy-MM-dd}.%i"
